In [22]:
# 1

In [23]:
import numpy as np

In [24]:
from functools import reduce


def reducer_concat(el_prev, el):
        # el_prev — предшествующий элемент
        # el — текущий элемент
        return el_prev + [el[0]]*el[1]


np.random.seed(18182)
a = np.random.randint(15, size=60)
print(f"array: {a}")
uniq, counts = np.unique(a, return_counts=True)
dictionary = dict((k, v) for k, v in zip(uniq, counts)) # {uniq : counts}
dictionary = dict(sorted(dictionary.items(), key=lambda item: item[1])) # sort by value
res = reduce(reducer_concat, dictionary.items(), [])
print(f"sorted: {res}")

array: [10  3 11 12  1  1 13  1  5  3 13  4 10  7  0  0  9  5  7  0  5  4 12  9
  4 14  7  9  4  8  5  9  3  8  4 13  4 12  0 14 13 12  8  3  3  8  2  2
 14  4 13 12 14  9  7  5  8 13 12  4]
sorted: [11, 2, 2, 10, 10, 1, 1, 1, 0, 0, 0, 0, 7, 7, 7, 7, 14, 14, 14, 14, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 4, 4, 4, 4, 4, 4, 4, 4]


In [25]:
# 2

In [26]:
np.random.seed(1)
h, w, color_depth = 64, 64, 4096
im = np.random.randint(color_depth, size=(h,w))
im = im.ravel()
print(len(np.unique(im)))

2579


In [27]:
# 3

In [28]:
def moving_avg(vec, per):
    cumsum = np.cumsum(np.insert(vec, 0, 0)) # insert 0 to begin and count cumsum
    return (cumsum[per:] - cumsum[:-per]) / per

In [29]:
np.random.seed(181)
vect = np.random.randint(40, size=10)
print(moving_avg(vect, 3))

[21.33333333 21.66666667 34.33333333 26.33333333 22.33333333 13.
 19.66666667 17.        ]


In [30]:
# 4

In [31]:
matrix = np.array([[1, 2, 3],
                [6, 8, 10],
                [1, 21, 6],
                [3, 4, 5],
                [10, 11, 18],
                [140, 100, 10]])

a, b, c = np.hsplit(matrix, 3)
# зануление сторон треугольника, если сторона = 0 -> треугольник невозможен
# проверка 3 раза, чтобы учесть зануление на предыдущей проверке и получить все стороны = 0
a = np.where(a < b + c, a, 0)
b = np.where(b < a + c, b, 0)
c = np.where(c < a + b, c, 0)

a = np.where(a < b + c, a, 0)
b = np.where(b < a + c, b, 0)
c = np.where(c < a + b, c, 0)

a = np.where(a < b + c, a, 0)
b = np.where(b < a + c, b, 0)
c = np.where(c < a + b, c, 0)

a = a[(a > 0)]
b = b[(b > 0)]
c = c[(c > 0)]

res = np.column_stack([a, b, c])
print(res)

[[ 6  8 10]
 [ 3  4  5]
 [10 11 18]]
